<?php View::content() ?>
<?php echo Tag::css("jquery.bootstrap") ?>
<h1>Procedimientos</h1>
<?php if (!empty($procedimientos)): ?>
	<table class="table">
		<thead>
			<th>Id</th>
			<th>Archivo</th>
			<th>Descripción</th>
			<th>Creado</th>
			<th></th>
		</thead>
		<?php foreach ($procedimientos as $key => $value): ?>
			<tr>
				<td><?php echo $value->id ?></td>
				<td><?php echo Html::link($value->url,"Descargar") ?></td>
				<td><?php echo $value->descripcion ?></td>
				<td><?php echo $value->created_at ?></td>
				<td>
					<div class="btn-group btn-group-xs" role="group" aria-label="...">
						<?php echo Html::link("procedimientos/editar/{$value->id}","Editar",'class="btn btn-default btn-xs"') ?>
						<?php echo Js::link("procedimientos/eliminar/{$value->id}","Eliminar",'Esta Seguro de Eliminar?','btn btn-default btn-xs') ?>
					</div>
				</td>
			</tr>
		<?php endforeach ?>
	</table>
	<?php echo Html::link("procedimientos/agregar","Agregar Nuevo") ?>
	<?php else: ?>
		<p>
			<h3>NO HAY ARCHIVOS AGREGADOS</h3>
			<?php echo Html::link("procedimientos/agregar","Agregar") ?>
		</p>
<?php endif ?>
<?php echo Tag::js("jquery/jquery.min") ?>
<?php echo Tag::js("jquery/jquery.datatables") ?>
<?php echo Tag::js("jquery/jquery.datatables.bootstrap") ?>
<script type="text/javascript">
	$(document).ready(function(){
		$('.table').DataTable( {"language": {
        "sProcessing":    "Procesando...",
        "sLengthMenu":    "Mostrar _MENU_ registros",
        "sZeroRecords":   "No se encontraron resultados",
        "sEmptyTable":    "Ningún dato disponible en esta tabla",
        "sInfo":          "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
        "sInfoEmpty":     "Mostrando registros del 0 al 0 de un total de 0 registros",
        "sInfoFiltered":  "(filtrado de un total de _MAX_ registros)",
        "sInfoPostFix":   "",
        "sSearch":        "Buscar:",
        "sUrl":           "",
        "sInfoThousands":  ",",
        "sLoadingRecords": "Cargando...",
        "oPaginate": {
            "sFirst":    "Primero",
            "sLast":    "Último",
            "sNext":    "Siguiente",
            "sPrevious": "Anterior"
        },
        "oAria": {
            "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
            "sSortDescending": ": Activar para ordenar la columna de manera descendente"
        }
    }
    });
	})
</script>